# Generated by Django 2.0.2 on 2020-03-13 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantitySold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Err',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(default='', max_length=250)),
                ('file_name', models.CharField(default='', max_length=250)),
                ('func_name', models.CharField(default='', max_length=250)),
                ('err', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FbAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryStats', models.TextField(default='')),
                ('genderStats', models.TextField(default='')),
                ('ageStats', models.TextField(default='')),
                ('asy_id', models.TextField(default='')),
                ('isIg', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('createdOn', models.TextField(default='')),
                ('privacyScope', models.TextField(default='')),
                ('minAge', models.TextField(default='')),
                ('maxAge', models.TextField(default='')),
                ('actor', models.TextField(default='')),
                ('countries', models.TextField(default='')),
                ('genders', models.TextField(default='')),
                ('snapshot', models.TextField(default='')),
                ('attachments', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('adType', models.TextField(default='')),
                ('linkToAd', models.TextField(default='')),
                ('mainAttachment', models.TextField(default='')),
                ('height', models.TextField(default='')),
                ('likeNum', models.TextField(default='')),
                ('commentsNum', models.TextField(default='')),
                ('shareNum', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productId', models.CharField(default='', max_length=250)),
                ('rating', models.FloatField(default=0.0)),
                ('productTitle', models.CharField(default='', max_length=250)),
                ('minPrice', models.FloatField(default=0.0)),
                ('maxPrice', models.FloatField(default=0.0)),
                ('storeName', models.CharField(default='', max_length=250)),
                ('totSalesCount', models.IntegerField(default=0.0)),
                ('shippingCountries', models.CharField(default='', max_length=250)),
                ('stockAvailable', models.IntegerField(default=0.0)),
                ('storeRating', models.FloatField(default=0.0)),
                ('productListingHasVideo', models.BooleanField(default=False)),
                ('imageUrl', models.URLField(default='')),
                ('logisticsReliability', models.CharField(default='', max_length=100)),
                ('sellerDsSupplier', models.BooleanField(default=False)),
                ('storeUrl', models.URLField(default='')),
                ('avgDailySale', models.FloatField(default=0.0)),
                ('dailySaleVariance', models.FloatField(default=11111.0)),
                ('shippingPrice', models.FloatField(default=0.0)),
                ('shippingCompany', models.CharField(default='', max_length=250)),
                ('commitDay', models.IntegerField(default=0)),
                ('estimatedDeliveryDayMin', models.IntegerField(default=0)),
                ('estimatedDeliveryDayMax', models.IntegerField(default=0)),
                ('trackingAvailable', models.BooleanField(default=False)),
                ('nums', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='dailysale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Product'),
        ),
    ]
