# Generated by Django 2.1.5 on 2019-09-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieUrls',
            new_name='CategorieUrl',
        ),
    ]
